import * as React from "react";
import * as Types from "./types";

declare function NewJobStep4(props: {
  as?: React.ElementType;
  slotAutomateScreeningToggle?: Types.Devlink.Slot;
  onClickAutomateScreeningCheck1?: Types.Devlink.RuntimeProps;
  isAutomatedScreeningChecked1?: Types.Visibility.VisibilityConditions;
  onClickAutomatedScreeningCheck2?: Types.Devlink.RuntimeProps;
  isAutomatedScreeningChecked2?: Types.Visibility.VisibilityConditions;
  slotAutomatedScreeningCount1?: Types.Devlink.Slot;
  slotAutomatedScreeningCount2?: Types.Devlink.Slot;
  slotResumeJdToggle?: Types.Devlink.Slot;
  slotShortlistCandidateToggle?: Types.Devlink.Slot;
  onClickShortlistCandidateCheck1?: Types.Devlink.RuntimeProps;
  onClickShortlistCandidateCheck2?: Types.Devlink.RuntimeProps;
  isShortlistCandidateChecked1?: Types.Visibility.VisibilityConditions;
  isShortlistCandidateChecked2?: Types.Visibility.VisibilityConditions;
  slotShortlistCandidateCount1?: Types.Devlink.Slot;
  slotShortlistCandidateCount2?: Types.Devlink.Slot;
  slotAiFeedbackToggle?: Types.Devlink.Slot;
  isHeaderVisible?: Types.Visibility.VisibilityConditions;
  isSettingHeadingVisible?: Types.Visibility.VisibilityConditions;
  onClickParticularTimeCheck?: Types.Devlink.RuntimeProps;
  onClickImmediatelyCheck?: Types.Devlink.RuntimeProps;
  isImmediatelyChecked?: Types.Visibility.VisibilityConditions;
  isParticularTimeChecked?: Types.Visibility.VisibilityConditions;
  slotTime?: Types.Devlink.Slot;
  isChooseTimeVisible?: Types.Visibility.VisibilityConditions;
  onClickDisqualifyCheck?: Types.Devlink.RuntimeProps;
  slotDisqualifyScore?: Types.Devlink.Slot;
}): React.JSX.Element;
