export const settings = [
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 1,
    triggerSelfSchedulingReminders: 0,
    requestReschedule: false,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 2,
    triggerSelfSchedulingReminders: 1,
    requestReschedule: true,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 1,
    triggerSelfSchedulingReminders: 1,
    requestReschedule: false,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 0,
    triggerSelfSchedulingReminders: 1,
    requestReschedule: true,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 2,
    triggerSelfSchedulingReminders: 1,
    requestReschedule: false,
    cancelInterview: true,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 1,
    triggerSelfSchedulingReminders: 0,
    requestReschedule: false,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 2,
    triggerSelfSchedulingReminders: 1,
    requestReschedule: false,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 1,
    triggerSelfSchedulingReminders: 0,
    requestReschedule: true,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 2,
    triggerSelfSchedulingReminders: 2,
    requestReschedule: false,
    cancelInterview: true,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 0,
    triggerSelfSchedulingReminders: 1,
    requestReschedule: true,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 2,
    triggerSelfSchedulingReminders: 1,
    requestReschedule: false,
    cancelInterview: true,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 1,
    triggerSelfSchedulingReminders: 0,
    requestReschedule: false,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 0,
    triggerSelfSchedulingReminders: 1,
    requestReschedule: false,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 1,
    triggerSelfSchedulingReminders: 0,
    requestReschedule: true,
    cancelInterview: false,
    selfSchedule: true,
  },
  {
    submitAvailability: true,
    triggerAvailabilityReminders: 2,
    triggerSelfSchedulingReminders: 1,
    requestReschedule: false,
    cancelInterview: true,
    selfSchedule: true,
  },
];

// type status  = 'in_progress' | 'comp'
