version: "3"

services:
  aglint_apis:
    container_name: aglint_apis
    image: aglint_apis:latest
    build:
      context: .
      dockerfile: ./apps/aglint-apis/Dockerfile
    restart: always
    ports:
      - 8080:8080

