import * as React from "react";
import * as Types from "./types";

declare function GlobalScheduleCard(props: {
  as?: React.ElementType;
  slotGlobalBadge?: Types.Devlink.Slot;
  textTime?: React.ReactNode;
  textDate?: React.ReactNode;
  slotRequestStatus?: Types.Devlink.Slot;
  isRequestStatusVisible?: Types.Visibility.VisibilityConditions;
  textPanelName?: React.ReactNode;
  iconPanel?: React.ReactNode;
  textDuration?: React.ReactNode;
  textPlaformName?: React.ReactNode;
  iconMeetingPlatform?: React.ReactNode;
  textRole?: React.ReactNode;
  textCandidateName?: React.ReactNode;
  slotButtonViewDetail?: Types.Devlink.Slot;
  onClickDropdown?: Types.Devlink.RuntimeProps;
  slotRequestDetail?: Types.Devlink.Slot;
  slotDropdownContent?: Types.Devlink.Slot;
  slotCheckbox?: Types.Devlink.Slot;
  isCheckboxVisible?: Types.Visibility.VisibilityConditions;
  isDateVisible?: Types.Visibility.VisibilityConditions;
  isTimeVisible?: Types.Visibility.VisibilityConditions;
  isSelectedVisible?: Types.Visibility.VisibilityConditions;
  isDropdownIconVisible?: Types.Visibility.VisibilityConditions;
  styleGrid?: Types.Devlink.RuntimeProps;
  isButtonBlockVisible?: Types.Visibility.VisibilityConditions;
  isRoleVisible?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
