import * as React from "react";
import * as Types from "./types";

declare function ScheduleTabOverview(props: {
  as?: React.ElementType;
  slotCandidateCard?: Types.Devlink.Slot;
  slotScheduleCard?: Types.Devlink.Slot;
  slotJoinMeetingButton?: Types.Devlink.Slot;
  onClickCopyLink?: Types.Devlink.RuntimeProps;
  textMeetingLink?: React.ReactNode;
  slotStatus?: Types.Devlink.Slot;
  textSchedule?: React.ReactNode;
  onClickInterviewModuleLink?: Types.Devlink.RuntimeProps;
  isInterviewersVisible?: Types.Visibility.VisibilityConditions;
  textInterviewModuleLink?: React.ReactNode;
  onClickReschedule?: Types.Devlink.RuntimeProps;
  onClickCancelSchedule?: Types.Devlink.RuntimeProps;
  isScheduleLinkVisible?: Types.Visibility.VisibilityConditions;
  slotRescheduleCard?: Types.Devlink.Slot;
  slotCandidate?: Types.Devlink.Slot;
  slotMembers?: Types.Devlink.Slot;
  isMembersVisible?: Types.Visibility.VisibilityConditions;
  isScheduleCardVisible?: Types.Visibility.VisibilityConditions;
  isMeetingLinkVisible?: Types.Visibility.VisibilityConditions;
  slotHeaderWithSlot?: Types.Devlink.Slot;
  slotOrganizer?: Types.Devlink.Slot;
  isOrganizerVisible?: Types.Visibility.VisibilityConditions;
  slotHiringTeam?: Types.Devlink.Slot;
  isHiringTeamVisible?: Types.Visibility.VisibilityConditions;
  textDuration?: React.ReactNode;
  textDate?: React.ReactNode;
  textTitle?: React.ReactNode;
  textPlatformName?: React.ReactNode;
  textTimeDuration?: React.ReactNode;
  slotButton?: Types.Devlink.Slot;
  slotPlatformIcon?: Types.Devlink.Slot;
  isOneToOneIconVisible?: Types.Visibility.VisibilityConditions;
  isPanelIconVisible?: Types.Visibility.VisibilityConditions;
  isDebriefIconVisible?: Types.Visibility.VisibilityConditions;
  slotAttendeesIcon?: Types.Devlink.Slot;
  onClickCopyCandidate?: Types.Devlink.RuntimeProps;
  onClickResendLink?: Types.Devlink.RuntimeProps;
  isResendLinkVisible?: Types.Visibility.VisibilityConditions;
  isCopyLinkVisible?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
