export type EventStatusType =
  | 'not_started'
  | 'in_progress'
  | 'failed'
  | 'completed';

export type EventNodeType =
  | 'SELF_SCHEDULE_LINK'
  | 'REQ_CAND_AVAIL_EMAIL_LINK'
  | 'CAND_AVAIL_REC'
  | 'CANCEL_AVAIL_REQ'
  | 'SELF_SCHEDULE_CANCEL'
  | 'RESEND_CAND_AVAIL_EMAIL_LINK'
  | 'CANCEL_INTERVIEW_MEETINGS'
  | 'MEETING_CANCEL_INFORM_INTERVIEWER_ORGANIZER'
  | 'REPLACE_ALTERNATIVE_INTERVIEWER'
  | 'SEND_INTERVIEWER_ATTENDANCE_RSVP'
  | 'SCHEDULE_FIRST_FOLLOWUP_AVAILABILITY_LINK'
  | 'SCHEDULE_FIRST_FOLLOWUP_SELF_SCHEDULE'
  | 'CANDIDATE_AVAILABILITY_RE_REQUESTED'
  | 'SCHEDULE_INTERVIEW_SLOT'
  | 'SCHEDULE_INTERVIEW_SLOT_FROM_CANDIDATE_AVAILABILITY'
  | 'SLOT_SUGGESTION'
  | 'CAND_CONFIRM_SLOT'
  | 'INTERVIEW_SCHEDULED'
  | 'RECRUITER_SCHEDULED';
