import * as React from "react";
import * as Types from "./types";

declare function JobDashboard(props: {
  as?: React.ElementType;
  textTopMatchPercentage?: React.ReactNode;
  textGoodMatchPercentage?: React.ReactNode;
  textAverageMatchPercentage?: React.ReactNode;
  textBelowAveragePercentage?: React.ReactNode;
  textNotAMatchPercentage?: React.ReactNode;
  textTopMatchCount?: React.ReactNode;
  textGoodMatchCount?: React.ReactNode;
  textAveageMatchCount?: React.ReactNode;
  textBelowAverageCount?: React.ReactNode;
  textNotAMatchCount?: React.ReactNode;
  slotPipeline?: Types.Devlink.Slot;
  slotModuleCard?: Types.Devlink.Slot;
  onClickAssistant?: Types.Devlink.RuntimeProps;
  textCandidateCount?: React.ReactNode;
  slotScheduleCardSmall?: Types.Devlink.Slot;
  slotLocationGraphBlock?: Types.Devlink.Slot;
  slotSkillGraphBlock?: Types.Devlink.Slot;
  slotExperienceGraph?: Types.Devlink.Slot;
  slotCardWithNumber?: Types.Devlink.Slot;
  isBanner?: Types.Visibility.VisibilityConditions;
  slotBanner?: Types.Devlink.Slot;
  onClickViewSchedule?: Types.Devlink.RuntimeProps;
  isViewScheduleVisible?: Types.Visibility.VisibilityConditions;
  onClickImport?: Types.Devlink.RuntimeProps;
  isImport?: Types.Visibility.VisibilityConditions;
  onClickCandidateList?: Types.Devlink.RuntimeProps;
  textScoreCount?: React.ReactNode;
  isScoring?: Types.Visibility.VisibilityConditions;
  slotScoringLoader?: Types.Devlink.Slot;
  onClickTopMatch?: Types.Devlink.RuntimeProps;
  onClickGoodMatch?: Types.Devlink.RuntimeProps;
  onClickAverageMatch?: Types.Devlink.RuntimeProps;
  onClickBelowAverage?: Types.Devlink.RuntimeProps;
  onClickNotaMatch?: Types.Devlink.RuntimeProps;
  slotJobRole?: Types.Devlink.Slot;
  isJobRoleVisible?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
