import * as React from "react";
import * as Types from "./types";

declare function MembersList(props: {
  as?: React.ElementType;
  slotImage?: Types.Devlink.Slot;
  isShadow?: Types.Visibility.VisibilityConditions;
  isReverseShadow?: Types.Visibility.VisibilityConditions;
  textName?: React.ReactNode;
  textDesignation?: React.ReactNode;
  textTime?: React.ReactNode;
  isWrongVisible?: Types.Visibility.VisibilityConditions;
  isCorrectVisible?: Types.Visibility.VisibilityConditions;
  isButtonVisible?: Types.Visibility.VisibilityConditions;
  onClickResendInvite?: Types.Devlink.RuntimeProps;
  onClickCopyInvite?: Types.Devlink.RuntimeProps;
  isDesignationVisible?: Types.Visibility.VisibilityConditions;
  isDetailVisible?: Types.Visibility.VisibilityConditions;
  textMail?: React.ReactNode;
  textLocation?: React.ReactNode;
  textTimeZone?: React.ReactNode;
  textTodayInterview?: React.ReactNode;
  textWeekInterview?: React.ReactNode;
  onClickViewInterviewDetail?: Types.Devlink.RuntimeProps;
  textJobTitle?: React.ReactNode;
  onClickAccept?: Types.Devlink.RuntimeProps;
  onClickDecline?: Types.Devlink.RuntimeProps;
  isAcceptVisible?: Types.Visibility.VisibilityConditions;
  isDeclineVisible?: Types.Visibility.VisibilityConditions;
  isAcceptDeclineVisibe?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
