import * as React from "react";
import * as Types from "./types";

declare function JobScreening(props: {
  as?: React.ElementType;
  textRole?: React.ReactNode;
  slotStopSubmission?: Types.Devlink.Slot;
  onClickAllApplicant?: Types.Devlink.RuntimeProps;
  onClickInterviewing?: Types.Devlink.RuntimeProps;
  countInterviewing?: React.ReactNode;
  onClickRejected?: Types.Devlink.RuntimeProps;
  countRejected?: React.ReactNode;
  onClickSelected?: Types.Devlink.RuntimeProps;
  countSelected?: React.ReactNode;
  slotSearch?: Types.Devlink.Slot;
  slotCandidateJobCard?: Types.Devlink.Slot;
  textApplicantsNumber?: React.ReactNode;
  textJobStatus?: React.ReactNode;
  slotAddCandidates?: Types.Devlink.Slot;
  countAll?: React.ReactNode;
  isAll?: Types.Visibility.VisibilityConditions;
  isInterviewing?: Types.Visibility.VisibilityConditions;
  isSelected?: Types.Visibility.VisibilityConditions;
  isRejected?: Types.Visibility.VisibilityConditions;
  onClickEditJob?: Types.Devlink.RuntimeProps;
  onClickWorkflow?: Types.Devlink.RuntimeProps;
  slotSelectActionBar?: Types.Devlink.Slot;
  bottomBarVisibility?: Types.Visibility.VisibilityConditions;
  jobLink?: Types.Basic.Link;
  linkActiveJobs?: Types.Basic.Link;
  slotJobStatus?: Types.Devlink.Slot;
  isTopbarVisible?: Types.Visibility.VisibilityConditions;
  interviewScore?: Types.Visibility.VisibilityConditions;
  selectAllCheckbox?: Types.Devlink.RuntimeProps;
  isSelectAllChecked?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
