import * as React from "react";
import * as Types from "./types";

declare function MemberListCard(props: {
  as?: React.ElementType;
  slotProfileImage?: Types.Devlink.Slot;
  textName?: React.ReactNode;
  textRole?: React.ReactNode;
  countCompletedSchedule?: React.ReactNode;
  onHoverDot?: Types.Devlink.RuntimeProps;
  onClickPauseInterview?: Types.Devlink.RuntimeProps;
  onClickResumeInterview?: Types.Devlink.RuntimeProps;
  onClickRemoveModule?: Types.Devlink.RuntimeProps;
  isPauseVisible?: Types.Visibility.VisibilityConditions;
  isResumeVisible?: Types.Visibility.VisibilityConditions;
  isScheduleCountVisible?: Types.Visibility.VisibilityConditions;
  isProfileVisible?: Types.Visibility.VisibilityConditions;
  isRoleVisible?: Types.Visibility.VisibilityConditions;
  isTrainingCompletedVisible?: Types.Visibility.VisibilityConditions;
  isTrainingProgessVisible?: Types.Visibility.VisibilityConditions;
  onClickApproveCandidate?: Types.Devlink.RuntimeProps;
  slotProgressBar?: Types.Devlink.Slot;
  isMoveToQualifierVisible?: Types.Visibility.VisibilityConditions;
  onClickMoveToQualifier?: Types.Devlink.RuntimeProps;
  isApproveCandidateButtonVisible?: Types.Visibility.VisibilityConditions;
  isPendingApprovalVisible?: Types.Visibility.VisibilityConditions;
  textPauseResumeDate?: React.ReactNode;
  isPauseResumeVisible?: Types.Visibility.VisibilityConditions;
  onClickCard?: Types.Devlink.RuntimeProps;
  isTextObjectiveVisible?: Types.Visibility.VisibilityConditions;
  textObjective?: React.ReactNode;
  isThreeDotVisible?: Types.Visibility.VisibilityConditions;
  slotTrainingProgressDetail?: Types.Devlink.Slot;
  isTrainingProgressDetailVisible?: Types.Visibility.VisibilityConditions;
  textConfirmed?: React.ReactNode;
  textCancel?: React.ReactNode;
  textTodayInterview?: React.ReactNode;
  textWeekInterview?: React.ReactNode;
  onClickDropdownIcon?: Types.Devlink.RuntimeProps;
  isDropdownIconVisible?: Types.Visibility.VisibilityConditions;
  textPause?: React.ReactNode;
}): React.JSX.Element;
