export const defaultRoles = [
  {
    name: 'admin',
    description:
      'Manage job postings, candidate information, interviews, reports, settings, workflows, and teams with the highest level of access.',
  },
  {
    name: 'hiring manager',
    description:
      'Assigned to jobs, view job postings, candidate information, interview schedules, and tasks.',
  },
  {
    name: 'recruiter',
    description:
      'Manage job postings, candidate information, interview scheduling, and task management.',
  },
  {
    name: 'interviewer',
    description: 'View interview schedules and related tasks.',
  },
  {
    name: 'recruiting coordinator',
    description:
      'Manage interview scheduling and coordination, as well as task updates related to interviews.',
  },
  {
    name: 'sourcer',
    description:
      'Add and manage candidate information and utilize sourcing tools to build talent pipelines.',
  },
] as const;

export const defaultPermissions = [
  { name: 'jobs_create', description: 'Create new job postings.' },
  { name: 'jobs_read', description: 'View existing job postings.' },
  { name: 'jobs_update', description: 'Update job postings.' },
  { name: 'jobs_delete', description: 'Delete job postings.' },
  { name: 'jobs_publish', description: 'Publish job postings.' },
  { name: 'jobs_unpublish', description: 'Unpublish job postings.' },
  { name: 'jobs_archive', description: 'Archive job postings.' },
  { name: 'jobs_restore', description: 'Restore archived job postings.' },
  {
    name: 'jobs_assignHiringManager',
    description: 'Assign a hiring manager to job postings.',
  },
  {
    name: 'jobs_assignRecruiter',
    description: 'Assign a recruiter to job postings.',
  },
  {
    name: 'jobs_assignCoordinator',
    description: 'Assign a recruiting coordinator to job postings.',
  },
  {
    name: 'jobs_assignSourcer',
    description: 'Assign a sourcer to job postings.',
  },
  { name: 'candidates_add', description: 'Add new candidates.' },
  { name: 'candidates_read', description: 'View candidate information.' },
  { name: 'candidates_update', description: 'Update candidate information.' },
  { name: 'candidates_delete', description: 'Delete candidate information.' },
  {
    name: 'candidates_moveStage',
    description:
      'Move candidates through different stages of the hiring process.',
  },
  { name: 'profileScore_view', description: 'View candidate profile scores.' },
  {
    name: 'profileScore_update',
    description: 'Update candidate profile scores.',
  },
  { name: 'interviews_read', description: 'View interview schedules.' },
  { name: 'interviews_update', description: 'Update interview schedules.' },
  { name: 'interviews_delete', description: 'Delete interview schedules.' },
  { name: 'reports_generate', description: 'Generate reports.' },
  { name: 'reports_view', description: 'View reports.' },
  { name: 'reports_export', description: 'Export reports.' },
  { name: 'settings_view', description: 'View settings.' },
  { name: 'settings_update', description: 'Update settings.' },
  { name: 'tasks_enabled', description: 'Enable task management features.' },
  { name: 'tasks_create', description: 'Create tasks.' },
  { name: 'tasks_read', description: 'View tasks.' },
  { name: 'tasks_update', description: 'Update tasks.' },
  { name: 'tasks_delete', description: 'Delete tasks.' },
  { name: 'scheduler_enabled', description: 'Enable scheduling features.' },
  { name: 'scheduler_create', description: 'Create schedules.' },
  { name: 'scheduler_read', description: 'View schedules.' },
  { name: 'scheduler_update', description: 'Update schedules.' },
  { name: 'scheduler_delete', description: 'Delete schedules.' },
  {
    name: 'scheduler_request_availability',
    description: 'Request candidate availability.',
  },
  {
    name: 'scheduler_send_scheduling',
    description: 'Send scheduling information to candidates.',
  },
  {
    name: 'scheduler_interview_types_create',
    description: 'Create interview types.',
  },
  {
    name: 'scheduler_interview_types_read',
    description: 'View interview types.',
  },
  {
    name: 'scheduler_interview_types_update',
    description: 'Update interview types.',
  },
  {
    name: 'scheduler_interviewer_edit',
    description: 'Edit interviewers for scheduled interviews.',
  },
  { name: 'jobs_enabled', description: 'Enable job management features.' },
  { name: 'sourcing_enabled', description: 'Enable sourcing features.' },
  {
    name: 'phone_screening_enabled',
    description: 'Enable phone screening features.',
  },
  { name: 'assessment_enabled', description: 'Enable assessment features.' },
  {
    name: 'integrations_enabled',
    description: 'Enable integrations with other systems.',
  },
  {
    name: 'company_setting_enabled',
    description: 'Enable company settings features.',
  },
  {
    name: 'workflow_enabled',
    description: 'Enable workflow management features.',
  },
  { name: 'workflow_create', description: 'Create workflows.' },
  { name: 'workflow_read', description: 'View workflows.' },
  { name: 'workflow_update', description: 'Update workflows.' },
  { name: 'workflow_delete', description: 'Delete workflows.' },
  { name: 'team_enabled', description: 'Enable team management features.' },
  { name: 'team_create', description: 'Create teams.' },
  { name: 'team_read', description: 'View teams.' },
  { name: 'team_update', description: 'Update teams.' },
  { name: 'team_delete', description: 'Delete teams.' },
  {
    name: 'settings_scheduler_enable',
    description: 'Enable scheduler settings.',
  },
  {
    name: 'settings_scheduler_update',
    description: 'Update scheduler settings.',
  },
  { name: 'settings_company_enable', description: 'Enable company settings.' },
  { name: 'settings_company_update', description: 'Update company settings.' },
  { name: 'settings_team_enable', description: 'Enable team settings.' },
  { name: 'settings_team_update', description: 'Update team settings.' },
  { name: 'settings_roles_enable', description: 'Enable roles settings.' },
  { name: 'settings_roles_update', description: 'Update roles settings.' },
] as const;

export const defaultRolePermissionRelation = {
  admin: [
    'jobs_create',
    'jobs_read',
    'jobs_update',
    'jobs_delete',
    'jobs_publish',
    'jobs_unpublish',
    'jobs_archive',
    'jobs_restore',
    'jobs_assignHiringManager',
    'jobs_assignRecruiter',
    'jobs_assignCoordinator',
    'jobs_assignSourcer',
    'candidates_add',
    'candidates_read',
    'candidates_update',
    'candidates_delete',
    'candidates_moveStage',
    'profileScore_view',
    'profileScore_update',
    'interviews_read',
    'interviews_update',
    'interviews_delete',
    'reports_generate',
    'reports_view',
    'reports_export',
    'settings_view',
    'settings_update',
    'tasks_enabled',
    'jobs_enabled',
    'scheduler_enabled',
    'sourcing_enabled',
    'phone_screening_enabled',
    'assessment_enabled',
    'integrations_enabled',
    'company_setting_enabled',
    'workflow_enabled',
    'workflow_create',
    'workflow_read',
    'workflow_update',
    'workflow_delete',
    'team_enabled',
    'team_create',
    'team_read',
    'team_update',
    'team_delete',
    'tasks_create',
    'tasks_read',
    'tasks_update',
    'tasks_delete',
    'scheduler_create',
    'scheduler_read',
    'scheduler_update',
    'scheduler_delete',
    'scheduler_request_availability',
    'scheduler_send_scheduling',
    'scheduler_interview_types_create',
    'scheduler_interview_types_read',
    'scheduler_interview_types_update',
    'scheduler_interviewer_edit',
    'settings_scheduler_enable',
    'settings_scheduler_update',
    'settings_company_enable',
    'settings_company_update',
    'settings_team_enable',
    'settings_team_update',
    'settings_roles_enable',
    'settings_roles_update',
  ],
  'hiring manager': [
    'jobs_create',
    'jobs_read',
    'jobs_update',
    'jobs_delete',
    'jobs_publish',
    'jobs_unpublish',
    'jobs_archive',
    'jobs_restore',
    'jobs_assignHiringManager',
    'jobs_assignRecruiter',
    'jobs_assignCoordinator',
    'jobs_assignSourcer',
    'candidates_add',
    'candidates_read',
    'candidates_update',
    'candidates_delete',
    'candidates_moveStage',
    'profileScore_view',
    'profileScore_update',
    'interviews_read',
    'interviews_update',
    'interviews_delete',
    'reports_generate',
    'reports_view',
    'reports_export',
    'settings_view',
    'settings_update',
    'tasks_enabled',
    'jobs_enabled',
    'scheduler_enabled',
    'sourcing_enabled',
    'phone_screening_enabled',
    'assessment_enabled',
    'integrations_enabled',
    'workflow_enabled',
    'workflow_create',
    'workflow_read',
    'workflow_update',
    'workflow_delete',
    'team_enabled',
    'team_create',
    'team_read',
    'team_update',
    'team_delete',
    'tasks_create',
    'tasks_read',
    'tasks_update',
    'tasks_delete',
    'scheduler_create',
    'scheduler_read',
    'scheduler_update',
    'scheduler_delete',
    'scheduler_request_availability',
    'scheduler_send_scheduling',
    'scheduler_interview_types_create',
    'scheduler_interview_types_read',
    'scheduler_interview_types_update',
    'scheduler_interviewer_edit',
    'settings_scheduler_enable',
    'settings_scheduler_update',
    'settings_team_enable',
    'settings_team_update',
    'settings_roles_enable',
    'settings_roles_update',
  ],
  recruiter: [
    'jobs_create',
    'jobs_read',
    'jobs_update',
    'jobs_delete',
    'jobs_publish',
    'jobs_unpublish',
    'jobs_archive',
    'jobs_restore',
    'jobs_assignHiringManager',
    'jobs_assignRecruiter',
    'jobs_assignCoordinator',
    'jobs_assignSourcer',
    'candidates_add',
    'candidates_read',
    'candidates_update',
    'candidates_delete',
    'candidates_moveStage',
    'profileScore_view',
    'profileScore_update',
    'interviews_read',
    'interviews_update',
    'interviews_delete',
    'reports_generate',
    'reports_view',
    'reports_export',
    'settings_view',
    'settings_update',
    'tasks_enabled',
    'jobs_enabled',
    'scheduler_enabled',
    'sourcing_enabled',
    'phone_screening_enabled',
    'assessment_enabled',
    'integrations_enabled',
    'workflow_enabled',
    'workflow_create',
    'workflow_read',
    'workflow_update',
    'workflow_delete',
    'team_enabled',
    'team_create',
    'team_read',
    'team_update',
    'team_delete',
    'tasks_create',
    'tasks_read',
    'tasks_update',
    'tasks_delete',
    'scheduler_create',
    'scheduler_read',
    'scheduler_update',
    'scheduler_delete',
    'scheduler_request_availability',
    'scheduler_send_scheduling',
    'scheduler_interview_types_create',
    'scheduler_interview_types_read',
    'scheduler_interview_types_update',
    'scheduler_interviewer_edit',
  ],
  interviewer: [
    'jobs_read',
    'candidates_read',
    'profileScore_view',
    'interviews_read',
    'interviews_update',
    'scheduler_enabled',
    'scheduler_update',
    'scheduler_interview_types_read',
  ],
  'recruiting coordinator': [
    'jobs_read',
    'jobs_update',
    'jobs_publish',
    'candidates_add',
    'candidates_read',
    'candidates_update',
    'candidates_moveStage',
    'profileScore_view',
    'profileScore_update',
    'interviews_read',
    'interviews_update',
    'reports_generate',
    'reports_view',
    'reports_export',
    'settings_view',
    'tasks_enabled',
    'jobs_enabled',
    'scheduler_enabled',
    'sourcing_enabled',
    'phone_screening_enabled',
    'assessment_enabled',
    'integrations_enabled',
    'workflow_enabled',
    'workflow_read',
    'tasks_create',
    'tasks_read',
    'tasks_update',
    'scheduler_create',
    'scheduler_read',
    'scheduler_update',
    'scheduler_delete',
    'scheduler_request_availability',
    'scheduler_send_scheduling',
    'scheduler_interview_types_create',
    'scheduler_interview_types_read',
    'scheduler_interview_types_update',
    'scheduler_interviewer_edit',
  ],
  sourcer: [
    'jobs_read',
    'candidates_read',
    'profileScore_view',
    'interviews_read',
    'reports_generate',
    'reports_view',
    'reports_export',
    'settings_view',
    'tasks_enabled',
    'jobs_enabled',
    'sourcing_enabled',
    'scheduler_read',
  ],
};
