export const defaultRoles = [
  {
    name: 'admin',
    description:
      'Manage job postings, candidate information, interviews, reports, settings, workflows, and teams with the highest level of access.',
  },
  {
    name: 'hiring manager',
    description:
      'Assigned to jobs, view job postings, candidate information, interview schedules, and tasks.',
  },
  {
    name: 'recruiter',
    description:
      'Manage job postings, candidate information, interview scheduling, and task management.',
  },
  {
    name: 'interviewer',
    description: 'View interview schedules and related tasks.',
  },
  {
    name: 'recruiting coordinator',
    description:
      'Manage interview scheduling and coordination, as well as task updates related to interviews.',
  },
  {
    name: 'sourcer',
    description:
      'Add and manage candidate information and utilize sourcing tools to build talent pipelines.',
  },
] as const;

export const defaultPermissions = [
  {
    name: 'candidates_update',
    title: 'candidates_update',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_read',
    title: 'View existing job postings',
    description: 'Allow the role to view current job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_delete',
    title: 'Delete job postings',
    description: 'Allow the role to delete job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_publish',
    title: 'Publish job postings',
    description: 'Allow the role to publish job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_archive',
    title: 'Archive job postings',
    description: 'Allow the role to archive job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_restore',
    title: 'Restore archived job postings',
    description: 'Allow the role to restore archived job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_assignRecruiter',
    title: 'Assign a recruiter to job postings',
    description: 'Allow the role to assign a recruiter to job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_assignSourcer',
    title: 'Assign a sourcer to job postings',
    description: 'Allow the role to assign a sourcer to job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'candidates_add',
    title: 'Add new applications',
    description: 'Allow the role to add new applications.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'candidates_read',
    title: 'View application information',
    description: 'Allow the role to view application details.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'profileScore_update',
    title: 'profileScore_update',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'interviews_read',
    title: 'interviews_read',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'interviews_update',
    title: 'interviews_update',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'interviews_delete',
    title: 'interviews_delete',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'reports_generate',
    title: 'reports_generate',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'reports_view',
    title: 'reports_view',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'reports_export',
    title: 'reports_export',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'phone_screening_enabled',
    title: 'phone_screening_enabled',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'assessment_enabled',
    title: 'assessment_enabled',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_create',
    title: 'scheduler_create',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_read',
    title: 'scheduler_read',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_update',
    title: 'scheduler_update',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_delete',
    title: 'scheduler_delete',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'team_delete',
    title: 'Remove User',
    description: 'Allow the role to remove users.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'candidates_moveStage',
    title: 'Move applications',
    description:
      'Allow the role to advance applications through hiring stages.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'profileScore_view',
    title: 'View application score',
    description: 'Allow the role to view application score.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_enabled',
    title: 'Enable Jobs App',
    description: 'By enabling this, the role will have access to the Jobs app.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_enabled',
    title: 'Enable Scheduling App',
    description:
      'By enabling this, the role will have access to the Scheduling app.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'integrations_enabled',
    title: 'Enable Integrations App',
    description:
      'By enabling this, the role will have access to the Integrations app.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'workflow_enabled',
    title: 'Enable Workflow App',
    description:
      'By enabling this, the role will have access to the Workflow app.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'workflow_create',
    title: 'Create workflows',
    description: 'Allow the role to create new workflows.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'workflow_read',
    title: 'View workflows',
    description: 'Allow the role to view existing workflows.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'workflow_delete',
    title: 'Delete workflows',
    description: 'Allow the role to delete workflows.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'team_read',
    title: 'View User Details',
    description: 'Allow the role to view existing users.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'tasks_create',
    title: 'Create tasks',
    description: 'Allow the role to create new tasks.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'tasks_read',
    title: 'View tasks',
    description: 'Allow the role to view existing tasks.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'tasks_delete',
    title: 'Delete tasks',
    description: 'Allow the role to delete tasks.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'settings_view',
    title: 'View Company Settings',
    description: 'View settings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'settings_update',
    title: 'Update Company Settings',
    description: 'Update settings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_request_availability',
    title: 'Request candidate availability.',
    description: 'Request candidate availability.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_interview_types_create',
    title: 'Create interview types.',
    description: 'Create interview types.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_interview_types_read',
    title: 'View interview types.',
    description: 'View interview types.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_interview_types_update',
    title: 'Update interview types.',
    description: 'Update interview types.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_interviewer_edit',
    title: 'Edit interviewers for scheduled interviews.',
    description: 'Edit interviewers for scheduled interviews.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'team_enabled',
    title: 'Enable User settings.',
    description: 'Enable User settings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'interviews_schedule',
    title: 'interviews_schedule',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_create',
    title: 'Create new job postings',
    description: 'Allow the role to create new job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_update',
    title: 'Update job postings',
    description: 'Allow the role to update existing job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_unpublish',
    title: 'Unpublish job postings',
    description: 'Allow the role to unpublish job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_assignHiringManager',
    title: 'Assign a hiring manager to job postings',
    description: 'Allow the role to assign a hiring manager to job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'jobs_assignCoordinator',
    title: 'Assign a recruiting coordinator to job postings',
    description:
      'Allow the role to assign a recruiting coordinator to job postings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'settings_scheduler_enable',
    title: 'settings_scheduler_enable',
    description: null,
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'candidates_delete',
    title: 'Delete application information',
    description: 'Allow the role to delete application information.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'tasks_enabled',
    title: 'Enable Tasks App',
    description:
      'By enabling this, the role will have access to the Tasks app.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'sourcing_enabled',
    title: 'Enable sourcing features.',
    description:
      'By enabling this, the role will have access to the Sourcing app.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'company_setting_enabled',
    title: 'Enable Company Settings App',
    description:
      'By enabling this, the role will have access to the Company Settings app.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'tasks_update',
    title: 'Update tasks',
    description: 'Allow the role to update existing tasks.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'scheduler_send_scheduling',
    title: 'Send scheduling information to candidates.',
    description: 'Send scheduling information to candidates.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'settings_scheduler_update',
    title: 'Update scheduler settings.',
    description: 'Update scheduler settings.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'settings_company_enable',
    title: 'View Company Details',
    description: 'Allow the role to view company details.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'settings_company_update',
    title: 'Manage Company Details',
    description: 'Allow the role to edit company details.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'team_create',
    title: 'Add New User',
    description: 'Allow the role to create new user.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'team_update',
    title: 'Update User Details',
    description: 'Allow the role to update existing users.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'workflow_update',
    title: 'Update workflows',
    description: 'Allow the role to update existing workflows.',
    dependency_tree: {
      child: [42],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'settings_roles_enable',
    title: 'View Roles',
    description: 'Allow the role to view roles.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'settings_roles_update',
    title: 'Manage Roles',
    description: 'Allow the role to add, edit, or remove roles.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'settings_team_enable',
    title: 'View Users',
    description: 'Allow the role to view user information.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
  {
    name: 'settings_team_update',
    title: 'Manage Users',
    description: 'Allow the role to add, edit, or remove users.',
    dependency_tree: {
      child: [],
      parent: null,
      sibling: null,
    },
  },
] as const;

export const defaultRolePermissionRelation = {
  admin: [
    'jobs_create',
    'jobs_read',
    'jobs_update',
    'jobs_delete',
    'jobs_publish',
    'jobs_unpublish',
    'jobs_archive',
    'jobs_restore',
    'jobs_assignHiringManager',
    'jobs_assignRecruiter',
    'jobs_assignCoordinator',
    'jobs_assignSourcer',
    'candidates_add',
    'candidates_read',
    'candidates_update',
    'candidates_delete',
    'candidates_moveStage',
    'profileScore_view',
    'profileScore_update',
    'interviews_read',
    'interviews_update',
    'interviews_delete',
    'reports_generate',
    'reports_view',
    'reports_export',
    'settings_view',
    'settings_update',
    'tasks_enabled',
    'jobs_enabled',
    'scheduler_enabled',
    'sourcing_enabled',
    'phone_screening_enabled',
    'assessment_enabled',
    'integrations_enabled',
    'company_setting_enabled',
    'workflow_enabled',
    'workflow_create',
    'workflow_read',
    'workflow_update',
    'workflow_delete',
    'team_enabled',
    'team_create',
    'team_read',
    'team_update',
    'team_delete',
    'tasks_create',
    'tasks_read',
    'tasks_update',
    'tasks_delete',
    'scheduler_create',
    'scheduler_read',
    'scheduler_update',
    'scheduler_delete',
    'scheduler_request_availability',
    'scheduler_send_scheduling',
    'scheduler_interview_types_create',
    'scheduler_interview_types_read',
    'scheduler_interview_types_update',
    'scheduler_interviewer_edit',
    'settings_scheduler_enable',
    'settings_scheduler_update',
    'settings_company_enable',
    'settings_company_update',
    'settings_team_enable',
    'settings_team_update',
    'settings_roles_enable',
    'settings_roles_update',
  ],
  'hiring manager': [
    'jobs_create',
    'jobs_read',
    'jobs_update',
    'jobs_delete',
    'jobs_publish',
    'jobs_unpublish',
    'jobs_archive',
    'jobs_restore',
    'jobs_assignHiringManager',
    'jobs_assignRecruiter',
    'jobs_assignCoordinator',
    'jobs_assignSourcer',
    'candidates_add',
    'candidates_read',
    'candidates_update',
    'candidates_delete',
    'candidates_moveStage',
    'profileScore_view',
    'profileScore_update',
    'interviews_read',
    'interviews_update',
    'interviews_delete',
    'reports_generate',
    'reports_view',
    'reports_export',
    'settings_view',
    'settings_update',
    'tasks_enabled',
    'jobs_enabled',
    'scheduler_enabled',
    'sourcing_enabled',
    'phone_screening_enabled',
    'assessment_enabled',
    'workflow_enabled',
    'workflow_create',
    'workflow_read',
    'workflow_update',
    'workflow_delete',
    'team_enabled',
    'team_create',
    'team_read',
    'team_update',
    'team_delete',
    'tasks_create',
    'tasks_read',
    'tasks_update',
    'tasks_delete',
    'scheduler_create',
    'scheduler_read',
    'scheduler_update',
    'scheduler_delete',
    'scheduler_request_availability',
    'scheduler_send_scheduling',
    'scheduler_interview_types_create',
    'scheduler_interview_types_read',
    'scheduler_interview_types_update',
    'scheduler_interviewer_edit',
    'settings_scheduler_enable',
    'settings_scheduler_update',
    'settings_team_enable',
    'settings_team_update',
    'settings_roles_enable',
    'settings_roles_update',
  ],
  recruiter: [
    'jobs_create',
    'jobs_read',
    'jobs_update',
    'jobs_delete',
    'jobs_publish',
    'jobs_unpublish',
    'jobs_archive',
    'jobs_restore',
    'jobs_assignHiringManager',
    'jobs_assignRecruiter',
    'jobs_assignCoordinator',
    'jobs_assignSourcer',
    'candidates_add',
    'candidates_read',
    'candidates_update',
    'candidates_delete',
    'candidates_moveStage',
    'profileScore_view',
    'profileScore_update',
    'interviews_read',
    'interviews_update',
    'interviews_delete',
    'reports_generate',
    'reports_view',
    'reports_export',
    'settings_view',
    'settings_update',
    'tasks_enabled',
    'jobs_enabled',
    'scheduler_enabled',
    'sourcing_enabled',
    'phone_screening_enabled',
    'assessment_enabled',
    'workflow_enabled',
    'workflow_create',
    'workflow_read',
    'workflow_update',
    'workflow_delete',
    'team_enabled',
    'team_create',
    'team_read',
    'team_update',
    'team_delete',
    'tasks_create',
    'tasks_read',
    'tasks_update',
    'tasks_delete',
    'scheduler_create',
    'scheduler_read',
    'scheduler_update',
    'scheduler_delete',
    'scheduler_request_availability',
    'scheduler_send_scheduling',
    'scheduler_interview_types_create',
    'scheduler_interview_types_read',
    'scheduler_interview_types_update',
    'scheduler_interviewer_edit',
  ],
  interviewer: [
    'jobs_read',
    'candidates_read',
    'profileScore_view',
    'interviews_read',
    'interviews_update',
    'scheduler_enabled',
    'scheduler_update',
    'scheduler_interview_types_read',
  ],
  'recruiting coordinator': [
    'jobs_read',
    'jobs_update',
    'jobs_publish',
    'candidates_add',
    'candidates_read',
    'candidates_update',
    'candidates_moveStage',
    'profileScore_view',
    'profileScore_update',
    'interviews_read',
    'interviews_update',
    'reports_generate',
    'reports_view',
    'reports_export',
    'settings_view',
    'tasks_enabled',
    'jobs_enabled',
    'scheduler_enabled',
    'sourcing_enabled',
    'phone_screening_enabled',
    'assessment_enabled',
    'workflow_enabled',
    'workflow_read',
    'tasks_create',
    'tasks_read',
    'tasks_update',
    'scheduler_create',
    'scheduler_read',
    'scheduler_update',
    'scheduler_delete',
    'scheduler_request_availability',
    'scheduler_send_scheduling',
    'scheduler_interview_types_create',
    'scheduler_interview_types_read',
    'scheduler_interview_types_update',
    'scheduler_interviewer_edit',
  ],
  sourcer: [
    'jobs_read',
    'candidates_read',
    'profileScore_view',
    'interviews_read',
    'reports_generate',
    'reports_view',
    'reports_export',
    'settings_view',
    'tasks_enabled',
    'jobs_enabled',
    'sourcing_enabled',
    'scheduler_read',
  ],
};
