export const industries = [
  'Advertising',
  'Aerospace',
  'Agriculture',
  'Automotive',
  'Banking',
  'Biotechnology',
  'Chemical',
  'Construction',
  'Consulting',
  'Consumer Goods',
  'Education',
  'Energy',
  'Entertainment',
  'Fashion',
  'Financial Services',
  'Food and Beverage',
  'Healthcare',
  'Hospitality',
  'Information Technology',
  'Insurance',
  'Manufacturing',
  'Media',
  'Mining',
  'Nonprofit',
  'Pharmaceutical',
  'Real Estate',
  'Retail',
  'Telecommunications',
  'Transportation',
  'Travel',
  'Utilities',
];
