export const pageRoutes = Object.freeze({
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESETPASSWORD: '/reset-password',
  HOMEPAGE: '/',
  JOBS: '/jobs',
  EDITJOBS: '/jobs/edit',
  COMPANY: '/company',
  CANDIDATES: '/candidates/history',
  AGLINTDB: '/candidates/aglintdb',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  ProfileLink: '/profile-link',
  MOCKTEST: '/assessment',
  JOBPOST: '/job-post/',
  COMPANYPOSTINGS: '/company-postings/',
  SUPPORT: '/support',
  CREATEJOB: '/jobs/new',
  ASSISTANT: '/assistant',
  PHONESCREEN: '/candidate-phone-screening',
  LOADING: '/loading',
  SCHEDULING: '/scheduling',
  SCHEDULINGPANEL: '/scheduling/panel',
  SCHEDULINGINTERVIEW: '/scheduling/interview',
});
