export const pageRoutes = Object.freeze({
  LOGIN: '/signup?step=signin',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESETPASSWORD: '/reset-password',
  HOMEPAGE: '/',
  JOBS: '/jobs',
  COMPANY: '/company',
  CANDIDATES: '/candidates',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  ProfileLink: '/profile-link',
  MOCKTEST: '/assessment',
  JOBPOST: '/job-post/',
  COMPANYPOSTINGS: '/company-postings/',
  SUPPORT: '/support',
  CREATEJOB: '/jobs/new',
  INTERVIEW: '/interview',
});
