const allLottie = {
  loader_dotted: {
    nm: 'loader_dotted',
    ddd: 0,
    h: 200,
    w: 200,
    meta: { g: '@lottiefiles/toolkit-js 0.33.2' },
    layers: [
      {
        ty: 4,
        nm: 'dotted Loader Outlines',
        sr: 1,
        st: 0,
        op: 155,
        ip: 0,
        hd: false,
        ddd: 0,
        bm: 0,
        hasMask: false,
        ao: 0,
        ks: {
          a: { a: 0, k: [100, 100, 0], ix: 1 },
          s: { a: 0, k: [100, 100, 100], ix: 6 },
          sk: { a: 0, k: 0 },
          p: {
            a: 1,
            k: [
              {
                o: { x: 0.167, y: 0.167 },
                i: { x: 0.833, y: 0.833 },
                s: [100, 100, 0],
                t: 0,
                ti: [0, 0, 0],
                to: [0, 0, 0],
              },
              { s: [100, 100, 0], t: 149 },
            ],
            ix: 2,
          },
          r: {
            a: 1,
            k: [
              {
                o: { x: 0.167, y: 0.167 },
                i: { x: 0.833, y: 0.833 },
                s: [0],
                t: 0,
              },
              { s: [359], t: 149 },
            ],
            ix: 10,
          },
          sa: { a: 0, k: 0 },
          o: { a: 0, k: 100, ix: 11 },
        },
        ef: [],
        shapes: [
          {
            ty: 'gr',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Group 1',
            ix: 1,
            cix: 2,
            np: 2,
            it: [
              {
                ty: 'sh',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ix: 1,
                d: 1,
                ks: {
                  a: 0,
                  k: {
                    c: true,
                    i: [
                      [-9.956, 0],
                      [0, -9.955],
                      [9.956, 0],
                      [0, 9.956],
                    ],
                    o: [
                      [9.956, 0],
                      [0, 9.956],
                      [-9.956, 0],
                      [0, -9.955],
                    ],
                    v: [
                      [0, -18.027],
                      [18.026, -0.001],
                      [0, 18.027],
                      [-18.026, -0.001],
                    ],
                  },
                  ix: 2,
                },
              },
              {
                ty: 'fl',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Graphic - Fill',
                nm: 'Fill 1',
                c: { a: 0, k: [0.2, 0.498, 0.7412], ix: 4 },
                r: 1,
                o: { a: 0, k: 100, ix: 5 },
              },
              {
                ty: 'tr',
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                sk: { a: 0, k: 0, ix: 4 },
                p: { a: 0, k: [170.631, 99.707], ix: 2 },
                r: { a: 0, k: 0, ix: 6 },
                sa: { a: 0, k: 0, ix: 5 },
                o: { a: 0, k: 100, ix: 7 },
              },
            ],
          },
          {
            ty: 'gr',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Group 2',
            ix: 2,
            cix: 2,
            np: 2,
            it: [
              {
                ty: 'sh',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ix: 1,
                d: 1,
                ks: {
                  a: 0,
                  k: {
                    c: true,
                    i: [
                      [-9.956, 0],
                      [0, -9.955],
                      [9.956, 0],
                      [0, 9.956],
                    ],
                    o: [
                      [9.956, 0],
                      [0, 9.956],
                      [-9.956, 0],
                      [0, -9.955],
                    ],
                    v: [
                      [-0.001, -18.027],
                      [18.027, -0.001],
                      [-0.001, 18.027],
                      [-18.027, -0.001],
                    ],
                  },
                  ix: 2,
                },
              },
              {
                ty: 'fl',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Graphic - Fill',
                nm: 'Fill 1',
                c: { a: 0, k: [0.2, 0.498, 0.7412], ix: 4 },
                r: 1,
                o: { a: 0, k: 100, ix: 5 },
              },
              {
                ty: 'tr',
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                sk: { a: 0, k: 0, ix: 4 },
                p: { a: 0, k: [29.513, 99.707], ix: 2 },
                r: { a: 0, k: 0, ix: 6 },
                sa: { a: 0, k: 0, ix: 5 },
                o: { a: 0, k: 100, ix: 7 },
              },
            ],
          },
          {
            ty: 'gr',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Group 3',
            ix: 3,
            cix: 2,
            np: 2,
            it: [
              {
                ty: 'sh',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ix: 1,
                d: 1,
                ks: {
                  a: 0,
                  k: {
                    c: true,
                    i: [
                      [0, 9.956],
                      [-9.955, 0],
                      [0, -9.956],
                      [9.956, 0],
                    ],
                    o: [
                      [0, -9.956],
                      [9.956, 0],
                      [0, 9.956],
                      [-9.955, 0],
                    ],
                    v: [
                      [-18.027, -0.001],
                      [-0.001, -18.027],
                      [18.027, -0.001],
                      [-0.001, 18.027],
                    ],
                  },
                  ix: 2,
                },
              },
              {
                ty: 'fl',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Graphic - Fill',
                nm: 'Fill 1',
                c: { a: 0, k: [0.2, 0.498, 0.7412], ix: 4 },
                r: 1,
                o: { a: 0, k: 100, ix: 5 },
              },
              {
                ty: 'tr',
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                sk: { a: 0, k: 0, ix: 4 },
                p: { a: 0, k: [100.072, 29.148], ix: 2 },
                r: { a: 0, k: 0, ix: 6 },
                sa: { a: 0, k: 0, ix: 5 },
                o: { a: 0, k: 100, ix: 7 },
              },
            ],
          },
          {
            ty: 'gr',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Group 4',
            ix: 4,
            cix: 2,
            np: 2,
            it: [
              {
                ty: 'sh',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ix: 1,
                d: 1,
                ks: {
                  a: 0,
                  k: {
                    c: true,
                    i: [
                      [0, 9.955],
                      [-9.955, 0],
                      [0, -9.956],
                      [9.956, 0],
                    ],
                    o: [
                      [0, -9.956],
                      [9.956, 0],
                      [0, 9.955],
                      [-9.955, 0],
                    ],
                    v: [
                      [-18.027, 0.001],
                      [-0.001, -18.027],
                      [18.027, 0.001],
                      [-0.001, 18.027],
                    ],
                  },
                  ix: 2,
                },
              },
              {
                ty: 'fl',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Graphic - Fill',
                nm: 'Fill 1',
                c: { a: 0, k: [0.2, 0.498, 0.7412], ix: 4 },
                r: 1,
                o: { a: 0, k: 100, ix: 5 },
              },
              {
                ty: 'tr',
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                sk: { a: 0, k: 0, ix: 4 },
                p: { a: 0, k: [100.072, 170.266], ix: 2 },
                r: { a: 0, k: 0, ix: 6 },
                sa: { a: 0, k: 0, ix: 5 },
                o: { a: 0, k: 100, ix: 7 },
              },
            ],
          },
          {
            ty: 'gr',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Group 5',
            ix: 5,
            cix: 2,
            np: 2,
            it: [
              {
                ty: 'sh',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ix: 1,
                d: 1,
                ks: {
                  a: 0,
                  k: {
                    c: true,
                    i: [
                      [7.04, 7.04],
                      [-7.04, 7.039],
                      [-7.039, -7.04],
                      [7.04, -7.04],
                    ],
                    o: [
                      [-7.04, -7.04],
                      [7.04, -7.04],
                      [7.04, 7.039],
                      [-7.039, 7.04],
                    ],
                    v: [
                      [-12.747, 12.746],
                      [-12.747, -12.747],
                      [12.747, -12.747],
                      [12.747, 12.746],
                    ],
                  },
                  ix: 2,
                },
              },
              {
                ty: 'fl',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Graphic - Fill',
                nm: 'Fill 1',
                c: { a: 0, k: [0.2, 0.498, 0.7412], ix: 4 },
                r: 1,
                o: { a: 0, k: 100, ix: 5 },
              },
              {
                ty: 'tr',
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                sk: { a: 0, k: 0, ix: 4 },
                p: { a: 0, k: [50.179, 49.815], ix: 2 },
                r: { a: 0, k: 0, ix: 6 },
                sa: { a: 0, k: 0, ix: 5 },
                o: { a: 0, k: 100, ix: 7 },
              },
            ],
          },
          {
            ty: 'gr',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Group 6',
            ix: 6,
            cix: 2,
            np: 2,
            it: [
              {
                ty: 'sh',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ix: 1,
                d: 1,
                ks: {
                  a: 0,
                  k: {
                    c: true,
                    i: [
                      [7.04, 7.04],
                      [-7.04, 7.04],
                      [-7.04, -7.04],
                      [7.039, -7.04],
                    ],
                    o: [
                      [-7.04, -7.04],
                      [7.04, -7.04],
                      [7.039, 7.04],
                      [-7.04, 7.04],
                    ],
                    v: [
                      [-12.746, 12.747],
                      [-12.746, -12.746],
                      [12.747, -12.746],
                      [12.747, 12.747],
                    ],
                  },
                  ix: 2,
                },
              },
              {
                ty: 'fl',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Graphic - Fill',
                nm: 'Fill 1',
                c: { a: 0, k: [0.2, 0.498, 0.7412], ix: 4 },
                r: 1,
                o: { a: 0, k: 100, ix: 5 },
              },
              {
                ty: 'tr',
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                sk: { a: 0, k: 0, ix: 4 },
                p: { a: 0, k: [149.964, 149.6], ix: 2 },
                r: { a: 0, k: 0, ix: 6 },
                sa: { a: 0, k: 0, ix: 5 },
                o: { a: 0, k: 100, ix: 7 },
              },
            ],
          },
          {
            ty: 'gr',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Group 7',
            ix: 7,
            cix: 2,
            np: 2,
            it: [
              {
                ty: 'sh',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ix: 1,
                d: 1,
                ks: {
                  a: 0,
                  k: {
                    c: true,
                    i: [
                      [7.04, -7.04],
                      [7.039, 7.04],
                      [-7.04, 7.04],
                      [-7.04, -7.04],
                    ],
                    o: [
                      [-7.04, 7.04],
                      [-7.04, -7.04],
                      [7.039, -7.04],
                      [7.04, 7.04],
                    ],
                    v: [
                      [12.747, 12.747],
                      [-12.747, 12.747],
                      [-12.747, -12.746],
                      [12.747, -12.746],
                    ],
                  },
                  ix: 2,
                },
              },
              {
                ty: 'fl',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Graphic - Fill',
                nm: 'Fill 1',
                c: { a: 0, k: [0.2, 0.498, 0.7412], ix: 4 },
                r: 1,
                o: { a: 0, k: 100, ix: 5 },
              },
              {
                ty: 'tr',
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                sk: { a: 0, k: 0, ix: 4 },
                p: { a: 0, k: [50.179, 149.6], ix: 2 },
                r: { a: 0, k: 0, ix: 6 },
                sa: { a: 0, k: 0, ix: 5 },
                o: { a: 0, k: 100, ix: 7 },
              },
            ],
          },
          {
            ty: 'gr',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Group 8',
            ix: 8,
            cix: 2,
            np: 2,
            it: [
              {
                ty: 'sh',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ix: 1,
                d: 1,
                ks: {
                  a: 0,
                  k: {
                    c: true,
                    i: [
                      [7.039, -7.04],
                      [7.04, 7.04],
                      [-7.04, 7.039],
                      [-7.04, -7.04],
                    ],
                    o: [
                      [-7.04, 7.04],
                      [-7.04, -7.04],
                      [7.04, -7.04],
                      [7.039, 7.039],
                    ],
                    v: [
                      [12.748, 12.746],
                      [-12.746, 12.746],
                      [-12.746, -12.747],
                      [12.748, -12.747],
                    ],
                  },
                  ix: 2,
                },
              },
              {
                ty: 'fl',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Graphic - Fill',
                nm: 'Fill 1',
                c: { a: 0, k: [0.2, 0.498, 0.7412], ix: 4 },
                r: 1,
                o: { a: 0, k: 100, ix: 5 },
              },
              {
                ty: 'tr',
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                sk: { a: 0, k: 0, ix: 4 },
                p: { a: 0, k: [149.964, 49.815], ix: 2 },
                r: { a: 0, k: 0, ix: 6 },
                sa: { a: 0, k: 0, ix: 5 },
                o: { a: 0, k: 100, ix: 7 },
              },
            ],
          },
        ],
        ind: 1,
      },
    ],
    v: '5.5.9',
    fr: 30,
    op: 150,
    ip: 0,
    assets: [],
  },
  loading_spinner: {
    nm: 'Comp 1',
    ddd: 0,
    h: 200,
    w: 200,
    meta: { g: '@lottiefiles/toolkit-js 0.33.2' },
    layers: [
      {
        ty: 4,
        nm: 'Shape Layer 2',
        sr: 1,
        st: 0,
        op: 300,
        ip: 0,
        hd: false,
        ddd: 0,
        bm: 0,
        hasMask: false,
        ao: 0,
        ks: {
          a: { a: 0, k: [-22.637, 19.301, 0], ix: 1 },
          s: { a: 0, k: [33.33333333333334, 33.33333333333334, 100], ix: 6 },
          sk: { a: 0, k: 0 },
          p: { a: 0, k: [100.02066666666668, 100.00000000000003, 0], ix: 2 },
          r: {
            a: 1,
            k: [
              {
                o: { x: 0.472, y: 0.326 },
                i: { x: 0.526, y: 0.673 },
                s: [0],
                t: 0,
              },
              { s: [183], t: 60 },
            ],
            ix: 10,
          },
          sa: { a: 0, k: 0 },
          o: { a: 0, k: 80, ix: 11 },
        },
        ef: [],
        shapes: [
          {
            ty: 'gr',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Ellipse 1',
            ix: 1,
            cix: 2,
            np: 3,
            it: [
              {
                ty: 'el',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Shape - Ellipse',
                nm: 'Ellipse Path 1',
                d: 1,
                p: { a: 0, k: [0, 0], ix: 3 },
                s: { a: 0, k: [368.602, 368.602], ix: 2 },
              },
              {
                ty: 'st',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Graphic - Stroke',
                nm: 'Stroke 1',
                lc: 2,
                lj: 1,
                ml: 4,
                o: { a: 0, k: 100, ix: 4 },
                w: { a: 0, k: 49, ix: 5 },
                c: { a: 0, k: [0, 0.4549, 0.6196], ix: 3 },
              },
              {
                ty: 'tr',
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                sk: { a: 0, k: 0, ix: 4 },
                p: { a: 0, k: [-22.699, 19.301], ix: 2 },
                r: { a: 0, k: 0, ix: 6 },
                sa: { a: 0, k: 0, ix: 5 },
                o: { a: 0, k: 100, ix: 7 },
              },
            ],
          },
          {
            ty: 'tm',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Filter - Trim',
            nm: 'Trim Paths 1',
            ix: 2,
            e: {
              a: 1,
              k: [
                { o: { x: 0.559, y: 0 }, i: { x: 0.504, y: 1 }, s: [1], t: 0 },
                { s: [50], t: 30 },
              ],
              ix: 2,
            },
            o: { a: 0, k: 0, ix: 3 },
            s: {
              a: 1,
              k: [
                { o: { x: 0.579, y: 0 }, i: { x: 0.438, y: 1 }, s: [0], t: 30 },
                { s: [49], t: 60 },
              ],
              ix: 1,
            },
            m: 1,
          },
        ],
        ind: 1,
      },
      {
        ty: 4,
        nm: 'Shape Layer 1',
        sr: 1,
        st: 0,
        op: 300,
        ip: 0,
        hd: false,
        ddd: 0,
        bm: 0,
        hasMask: false,
        ao: 0,
        ks: {
          a: { a: 0, k: [0, 0, 0], ix: 1 },
          s: { a: 0, k: [33.33333333333334, 33.33333333333334, 100], ix: 6 },
          sk: { a: 0, k: 0 },
          p: { a: 0, k: [107.56633333333339, 93.56633333333338, 0], ix: 2 },
          r: { a: 0, k: 0, ix: 10 },
          sa: { a: 0, k: 0 },
          o: { a: 0, k: 10, ix: 11 },
        },
        ef: [],
        shapes: [
          {
            ty: 'gr',
            bm: 0,
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Ellipse 1',
            ix: 1,
            cix: 2,
            np: 3,
            it: [
              {
                ty: 'el',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Shape - Ellipse',
                nm: 'Ellipse Path 1',
                d: 1,
                p: { a: 0, k: [0, 0], ix: 3 },
                s: { a: 0, k: [368.602, 368.602], ix: 2 },
              },
              {
                ty: 'st',
                bm: 0,
                hd: false,
                mn: 'ADBE Vector Graphic - Stroke',
                nm: 'Stroke 1',
                lc: 2,
                lj: 1,
                ml: 4,
                o: { a: 0, k: 100, ix: 4 },
                w: { a: 0, k: 49, ix: 5 },
                c: { a: 0, k: [0, 0.4549, 0.6196], ix: 3 },
              },
              {
                ty: 'tr',
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                sk: { a: 0, k: 0, ix: 4 },
                p: { a: 0, k: [-22.699, 19.301], ix: 2 },
                r: { a: 0, k: 0, ix: 6 },
                sa: { a: 0, k: 0, ix: 5 },
                o: { a: 0, k: 100, ix: 7 },
              },
            ],
          },
        ],
        ind: 2,
      },
    ],
    v: '5.5.0',
    fr: 30,
    op: 60,
    ip: 0,
    assets: [],
  },
};
export default allLottie;
