import {
  additionalRescheduleNotes,
  cancelReason,
  candidates,
  date_range,
  dates,
  interviewer,
  jobDetails,
  organizer,
  rescheduleReason,
  selfSchedulingLink,
  time,
} from "./variables";

export const emailVariablePayloads = {
  debrief_email_interviewer: [
    ...interviewer,
    ...candidates,
    ...jobDetails,
    ...organizer,
  ],
  applicationRecieved_email_applicant: [...candidates, ...jobDetails],
  interviewCancel_email_applicant: [...organizer, ...candidates, ...jobDetails],
  agent_email_candidate: [
    ...organizer,
    ...candidates,
    ...jobDetails,
    date_range,
  ],
  confInterview_email_organizer: [...organizer, ...candidates, ...jobDetails],
  confirmInterview_email_applicant: [
    ...organizer,
    ...candidates,
    ...jobDetails,
  ],
  applicantReject_email_applicant: [...candidates, ...jobDetails],
  availabilityReqResend_email_candidate: [
    ...candidates,
    ...jobDetails,
    ...organizer,
  ],
  InterviewCancelReq_email_recruiter: [
    ...organizer,
    ...candidates,
    cancelReason,
    additionalRescheduleNotes,
    ...jobDetails,
  ],
  interReschedReq_email_recruiter: [
    ...organizer,
    ...candidates,
    rescheduleReason,
    additionalRescheduleNotes,
    ...jobDetails,
    ...dates,
  ],

  interviewStart_email_applicant: [
    ...candidates,
    ...jobDetails,
    ...organizer,
    ...dates,
    time,
  ],
  interviewStart_email_interviewers: [
    ...jobDetails,
    ...candidates,
    ...interviewer,
    ...organizer,
    ...dates,
    time,
  ],
  sendSelfScheduleRequest_email_applicant: [
    ...candidates,
    ...jobDetails,
    ...organizer,
    selfSchedulingLink,
  ],
  sendAvailReqReminder_email_applicant: [
    ...candidates,
    ...jobDetails,
    ...organizer,
  ],
  selfScheduleReminder_email_applicant: [
    ...candidates,
    ...jobDetails,
    ...organizer,
  ],
  sendAvailabilityRequest_email_applicant: [
    ...candidates,
    ...jobDetails,

    ...organizer,
  ],
  rescheduleSelfSchedule_email_applicant: [
    ...candidates,
    ...jobDetails,
    ...organizer,
  ],
  interviewDetails_calender_interviewer: [
    ...candidates,
    ...jobDetails,
    ...interviewer,
    ...organizer,
  ],
  interviewStart_email_organizer: [...candidates, ...jobDetails, ...organizer],
  meetingAccepted_email_organizer: [
    ...candidates,
    ...interviewer,
    ...organizer,
    ...jobDetails,
  ],
  meetingDeclined_email_organizer: [
    ...candidates,
    ...interviewer,
    ...organizer,
    ...jobDetails,
  ],
  interviewEnd_email_interviewerForFeedback: [
    ...candidates,
    ...interviewer,
    ...organizer,
    ...jobDetails,
  ],
};
