create table "public"."rp_token_usage" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "application_id" uuid not null,
    "job_id" uuid,
    "task" text,
    "token_used_json" jsonb not null,
    "total_token_used" numeric not null default '0'::numeric
);


CREATE UNIQUE INDEX rp_token_usage_pkey ON public.rp_token_usage USING btree (id);

alter table "public"."rp_token_usage" add constraint "rp_token_usage_pkey" PRIMARY KEY using index "rp_token_usage_pkey";


