create table "public"."candidate_request_availability" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date_range" jsonb default '{"end_date": null, "start_date": null}'::jsonb,
    "session_ids" jsonb,
    "availability" jsonb default '{}'::jsonb,
    "number_of_days" integer,
    "number_of_slots" bigint,
    "is_task_created" boolean default true,
    "total_slots" bigint
);


alter table "public"."candidate_request_availability" enable row level security;

CREATE UNIQUE INDEX candidate_request_availability_pkey ON public.candidate_request_availability USING btree (id);

alter table "public"."candidate_request_availability" add constraint "candidate_request_availability_pkey" PRIMARY KEY using index "candidate_request_availability_pkey";

grant delete on table "public"."candidate_request_availability" to "anon";

grant insert on table "public"."candidate_request_availability" to "anon";

grant references on table "public"."candidate_request_availability" to "anon";

grant select on table "public"."candidate_request_availability" to "anon";

grant trigger on table "public"."candidate_request_availability" to "anon";

grant truncate on table "public"."candidate_request_availability" to "anon";

grant update on table "public"."candidate_request_availability" to "anon";

grant delete on table "public"."candidate_request_availability" to "authenticated";

grant insert on table "public"."candidate_request_availability" to "authenticated";

grant references on table "public"."candidate_request_availability" to "authenticated";

grant select on table "public"."candidate_request_availability" to "authenticated";

grant trigger on table "public"."candidate_request_availability" to "authenticated";

grant truncate on table "public"."candidate_request_availability" to "authenticated";

grant update on table "public"."candidate_request_availability" to "authenticated";

grant delete on table "public"."candidate_request_availability" to "service_role";

grant insert on table "public"."candidate_request_availability" to "service_role";

grant references on table "public"."candidate_request_availability" to "service_role";

grant select on table "public"."candidate_request_availability" to "service_role";

grant trigger on table "public"."candidate_request_availability" to "service_role";

grant truncate on table "public"."candidate_request_availability" to "service_role";

grant update on table "public"."candidate_request_availability" to "service_role";


