create table
  public.roles (
    id uuid not null default uuid_generate_v4 (),
    recruiter_id uuid not null,
    name text not null,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    constraint roles_pkey primary key (id),
    constraint roles_recruiter_id_fkey foreign key (recruiter_id) references recruiter (id)
  ) tablespace pg_default;

create table
  public.permissions (
    id bigint generated by default as identity,
    recruiter_id uuid null,
    name text not null,
    created_at timestamp without time zone null default current_timestamp,
    updated_at timestamp without time zone null default current_timestamp,
    constraint permissions_pkey primary key (id),
    constraint permissions_name_key unique (name),
    constraint permissions_recruiter_id_fkey foreign key (recruiter_id) references recruiter (id)
  ) tablespace pg_default;

  create table
  public.role_permissions (
    role_id uuid not null,
    permission_id integer not null,
    recruiter_id uuid not null,
    constraint role_permissions_pkey primary key (role_id, permission_id, recruiter_id),
    constraint role_permissions_permission_id_fkey foreign key (permission_id) references permissions (id),
    constraint role_permissions_recruiter_id_fkey foreign key (recruiter_id) references recruiter (id),
    constraint role_permissions_role_id_fkey foreign key (role_id) references roles (id)
  ) tablespace pg_default;