create table "public"."supabase-branching" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
);


alter table "public"."supabase-branching" enable row level security;

CREATE UNIQUE INDEX "supabase-branching_pkey" ON public."supabase-branching" USING btree (id);

alter table "public"."supabase-branching" add constraint "supabase-branching_pkey" PRIMARY KEY using index "supabase-branching_pkey";

grant delete on table "public"."supabase-branching" to "anon";

grant insert on table "public"."supabase-branching" to "anon";

grant references on table "public"."supabase-branching" to "anon";

grant select on table "public"."supabase-branching" to "anon";

grant trigger on table "public"."supabase-branching" to "anon";

grant truncate on table "public"."supabase-branching" to "anon";

grant update on table "public"."supabase-branching" to "anon";

grant delete on table "public"."supabase-branching" to "authenticated";

grant insert on table "public"."supabase-branching" to "authenticated";

grant references on table "public"."supabase-branching" to "authenticated";

grant select on table "public"."supabase-branching" to "authenticated";

grant trigger on table "public"."supabase-branching" to "authenticated";

grant truncate on table "public"."supabase-branching" to "authenticated";

grant update on table "public"."supabase-branching" to "authenticated";

grant delete on table "public"."supabase-branching" to "service_role";

grant insert on table "public"."supabase-branching" to "service_role";

grant references on table "public"."supabase-branching" to "service_role";

grant select on table "public"."supabase-branching" to "service_role";

grant trigger on table "public"."supabase-branching" to "service_role";

grant truncate on table "public"."supabase-branching" to "service_role";

grant update on table "public"."supabase-branching" to "service_role";


