create type "public"."workflow_action_medium" as enum ('email', 'slack');

create type "public"."workflow_action_target" as enum ('applicant', 'recruiter', 'hiring_manager', 'interviewers', 'recruiting_coordinator', 'custom');

create type "public"."workflow_phase" as enum ('before', 'after', 'now');

create type "public"."workflow_trigger" as enum ('application_new', 'application_phone_screening', 'application_assessment', 'application_interview', 'application_qualified', 'application_disqualified', 'booking_link_sent', 'interview_start');

create table "public"."workflow" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "trigger" workflow_trigger,
    "phase" workflow_phase,
    "interval" numeric not null default '0'::numeric,
    "title" text
);


create table "public"."workflow_action" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "workflow_id" uuid default gen_random_uuid(),
    "target" workflow_action_target,
    "medium" workflow_action_medium,
    "order" numeric not null,
    "payload" jsonb
);


create table "public"."workflow_action_logs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "started_at" timestamp with time zone,
    "completed_at" timestamp with time zone,
    "tries" numeric not null default '0'::numeric,
    "status" application_processing_status not null default 'not started'::application_processing_status,
    "workflow_id" uuid not null,
    "workflow_action_id" uuid not null,
    "application_id" uuid not null
);


create table "public"."workflow_job_relation" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "job_id" uuid default gen_random_uuid(),
    "workflow_id" uuid default gen_random_uuid()
);


CREATE UNIQUE INDEX workflow_action_logs_pkey ON public.workflow_action_logs USING btree (id);

CREATE UNIQUE INDEX workflow_action_pkey ON public.workflow_action USING btree (id);

CREATE UNIQUE INDEX workflow_job_relation_pkey ON public.workflow_job_relation USING btree (id);

CREATE UNIQUE INDEX workflow_pkey ON public.workflow USING btree (id);

alter table "public"."workflow" add constraint "workflow_pkey" PRIMARY KEY using index "workflow_pkey";

alter table "public"."workflow_action" add constraint "workflow_action_pkey" PRIMARY KEY using index "workflow_action_pkey";

alter table "public"."workflow_action_logs" add constraint "workflow_action_logs_pkey" PRIMARY KEY using index "workflow_action_logs_pkey";

alter table "public"."workflow_job_relation" add constraint "workflow_job_relation_pkey" PRIMARY KEY using index "workflow_job_relation_pkey";

alter table "public"."workflow_action" add constraint "workflow_action_workflow_id_fkey" FOREIGN KEY (workflow_id) REFERENCES workflow(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."workflow_action" validate constraint "workflow_action_workflow_id_fkey";

alter table "public"."workflow_action_logs" add constraint "workflow_action_logs_application_id_fkey" FOREIGN KEY (application_id) REFERENCES applications(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."workflow_action_logs" validate constraint "workflow_action_logs_application_id_fkey";

alter table "public"."workflow_action_logs" add constraint "workflow_action_logs_workflow_action_id_fkey" FOREIGN KEY (workflow_action_id) REFERENCES workflow_action(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."workflow_action_logs" validate constraint "workflow_action_logs_workflow_action_id_fkey";

alter table "public"."workflow_action_logs" add constraint "workflow_action_logs_workflow_id_fkey" FOREIGN KEY (workflow_id) REFERENCES workflow(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."workflow_action_logs" validate constraint "workflow_action_logs_workflow_id_fkey";

alter table "public"."workflow_job_relation" add constraint "workflow_job_relation_job_id_fkey" FOREIGN KEY (job_id) REFERENCES public_jobs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."workflow_job_relation" validate constraint "workflow_job_relation_job_id_fkey";

alter table "public"."workflow_job_relation" add constraint "workflow_job_relation_workflow_id_fkey" FOREIGN KEY (workflow_id) REFERENCES workflow(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."workflow_job_relation" validate constraint "workflow_job_relation_workflow_id_fkey";

grant delete on table "public"."workflow" to "anon";

grant insert on table "public"."workflow" to "anon";

grant references on table "public"."workflow" to "anon";

grant select on table "public"."workflow" to "anon";

grant trigger on table "public"."workflow" to "anon";

grant truncate on table "public"."workflow" to "anon";

grant update on table "public"."workflow" to "anon";

grant delete on table "public"."workflow" to "authenticated";

grant insert on table "public"."workflow" to "authenticated";

grant references on table "public"."workflow" to "authenticated";

grant select on table "public"."workflow" to "authenticated";

grant trigger on table "public"."workflow" to "authenticated";

grant truncate on table "public"."workflow" to "authenticated";

grant update on table "public"."workflow" to "authenticated";

grant delete on table "public"."workflow" to "service_role";

grant insert on table "public"."workflow" to "service_role";

grant references on table "public"."workflow" to "service_role";

grant select on table "public"."workflow" to "service_role";

grant trigger on table "public"."workflow" to "service_role";

grant truncate on table "public"."workflow" to "service_role";

grant update on table "public"."workflow" to "service_role";

grant delete on table "public"."workflow_action" to "anon";

grant insert on table "public"."workflow_action" to "anon";

grant references on table "public"."workflow_action" to "anon";

grant select on table "public"."workflow_action" to "anon";

grant trigger on table "public"."workflow_action" to "anon";

grant truncate on table "public"."workflow_action" to "anon";

grant update on table "public"."workflow_action" to "anon";

grant delete on table "public"."workflow_action" to "authenticated";

grant insert on table "public"."workflow_action" to "authenticated";

grant references on table "public"."workflow_action" to "authenticated";

grant select on table "public"."workflow_action" to "authenticated";

grant trigger on table "public"."workflow_action" to "authenticated";

grant truncate on table "public"."workflow_action" to "authenticated";

grant update on table "public"."workflow_action" to "authenticated";

grant delete on table "public"."workflow_action" to "service_role";

grant insert on table "public"."workflow_action" to "service_role";

grant references on table "public"."workflow_action" to "service_role";

grant select on table "public"."workflow_action" to "service_role";

grant trigger on table "public"."workflow_action" to "service_role";

grant truncate on table "public"."workflow_action" to "service_role";

grant update on table "public"."workflow_action" to "service_role";

grant delete on table "public"."workflow_action_logs" to "anon";

grant insert on table "public"."workflow_action_logs" to "anon";

grant references on table "public"."workflow_action_logs" to "anon";

grant select on table "public"."workflow_action_logs" to "anon";

grant trigger on table "public"."workflow_action_logs" to "anon";

grant truncate on table "public"."workflow_action_logs" to "anon";

grant update on table "public"."workflow_action_logs" to "anon";

grant delete on table "public"."workflow_action_logs" to "authenticated";

grant insert on table "public"."workflow_action_logs" to "authenticated";

grant references on table "public"."workflow_action_logs" to "authenticated";

grant select on table "public"."workflow_action_logs" to "authenticated";

grant trigger on table "public"."workflow_action_logs" to "authenticated";

grant truncate on table "public"."workflow_action_logs" to "authenticated";

grant update on table "public"."workflow_action_logs" to "authenticated";

grant delete on table "public"."workflow_action_logs" to "service_role";

grant insert on table "public"."workflow_action_logs" to "service_role";

grant references on table "public"."workflow_action_logs" to "service_role";

grant select on table "public"."workflow_action_logs" to "service_role";

grant trigger on table "public"."workflow_action_logs" to "service_role";

grant truncate on table "public"."workflow_action_logs" to "service_role";

grant update on table "public"."workflow_action_logs" to "service_role";

grant delete on table "public"."workflow_job_relation" to "anon";

grant insert on table "public"."workflow_job_relation" to "anon";

grant references on table "public"."workflow_job_relation" to "anon";

grant select on table "public"."workflow_job_relation" to "anon";

grant trigger on table "public"."workflow_job_relation" to "anon";

grant truncate on table "public"."workflow_job_relation" to "anon";

grant update on table "public"."workflow_job_relation" to "anon";

grant delete on table "public"."workflow_job_relation" to "authenticated";

grant insert on table "public"."workflow_job_relation" to "authenticated";

grant references on table "public"."workflow_job_relation" to "authenticated";

grant select on table "public"."workflow_job_relation" to "authenticated";

grant trigger on table "public"."workflow_job_relation" to "authenticated";

grant truncate on table "public"."workflow_job_relation" to "authenticated";

grant update on table "public"."workflow_job_relation" to "authenticated";

grant delete on table "public"."workflow_job_relation" to "service_role";

grant insert on table "public"."workflow_job_relation" to "service_role";

grant references on table "public"."workflow_job_relation" to "service_role";

grant select on table "public"."workflow_job_relation" to "service_role";

grant trigger on table "public"."workflow_job_relation" to "service_role";

grant truncate on table "public"."workflow_job_relation" to "service_role";

grant update on table "public"."workflow_job_relation" to "service_role";


