name: Lint

# Define when this workflow should run
on:
  push:
    branches:
      - main
      - development
      - staging

  pull_request:
    branches:
      - main
      - development
      - staging

# Set permissions for the workflow
permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest-4-cores # Use a larger runner

    steps:
      # Step 1: Check out the repository
      - name: Check out Git repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Cache Turborepo
      - name: Cache Turborepo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # Step 5: Run the linter for all workspaces
      - name: Run Linter
        run: npx turbo run lint --cache-dir=.turbo
        env:
          NODE_OPTIONS: --max-old-space-size=4096
