name: Lint and Preview Deploy

# Define when this workflow should run
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

# Set permissions for the workflow
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  preview-deploy:
    name: Preview Deploy to Vercel
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/development' # Only run on pushes to development branch

    steps:
      # Step 1: Check out the repository
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Step 2: Install Vercel CLI globally
      - name: Install Vercel CLI
        run: npm install -g vercel
      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          echo "Attempting to deploy..."
          # Deploy to Vercel with --no-wait option and save stdout and stderr to files
          vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} --yes --no-wait
