name: Lint

# Define when this workflow should run
on:
  push:
    branches: [main, development, staging]
  pull_request:
    branches: [main, development, staging]

# Set permissions for the workflow
permissions:
  checks: write
  contents: read

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Cache Turborepo
      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      # Step 5: Run the linter for all workspaces
      - name: Run Linter
        run: npx turbo run lint --cache-dir=.turbo
        env:
          NODE_OPTIONS: --max-old-space-size=4096
