create table "public"."ai_videos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "video_id" character varying,
    "video_url" character varying,
    "file_url" character varying,
    "error" jsonb
);


CREATE UNIQUE INDEX ai_videos_pkey ON public.ai_videos USING btree (id);

alter table "public"."ai_videos" add constraint "ai_videos_pkey" PRIMARY KEY using index "ai_videos_pkey";


